In [2]:
!pip install tensorflow pandas matplotlib  scikit-learn

In [3]:
import os

In [4]:
import pandas as pd

In [5]:
import tensorflow as tf
import numpy as np


In [6]:
df=pd.read_csv('C:\\Users\\yasmine\\Downloads\\comments\\train.csv')

In [7]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [8]:
df.iloc[0]['comment_text']

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [9]:
 df[df.columns[2:]].iloc[0]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 0, dtype: int64

In [10]:
from tensorflow.keras.layers import TextVectorization

In [11]:
y=df[df.columns[2:]].values
x=df['comment_text']
x

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [12]:
NB_W = 200000

In [13]:
vectorizer = TextVectorization(max_tokens=NB_W,
                              output_sequence_length=1800,
                              output_mode='int')

In [19]:
vectorizer.adapt(x.values)

In [20]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [21]:
vectorizer.get_vocabulary??


In [22]:
vectorized_text=vectorizer(x.values)

In [23]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [24]:
len(x)

159571

In [25]:
dataset=tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset=dataset.cache()
dataset=dataset.shuffle(160000)
dataset=dataset.batch(16)
dataset=dataset.prefetch(8) #helps prevent bottlenecks
#MACSHBAP-map,cache,sheuffle,batch,prefetch from_tensor_slices,list_file

In [26]:
batch_X,batch_y=dataset.as_numpy_iterator().next()
batch_X

array([[    8,    69,     8, ...,     0,     0,     0],
       [  165,   214,     6, ...,     0,     0,     0],
       [  171, 39397,    23, ...,     0,     0,     0],
       ...,
       [88850,    16,  2051, ...,     0,     0,     0],
       [  139,     7,     7, ...,     0,     0,     0],
       [37333,     2,  5986, ...,     0,     0,     0]], dtype=int64)

In [28]:
dataset

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 1800), dtype=tf.int64, name=None), TensorSpec(shape=(None, 6), dtype=tf.int64, name=None))>

In [29]:
batch_X.shape

(16, 1800)

In [30]:
batch_X,batch_y=dataset.as_numpy_iterator().next()
batch_X

array([[     8,     88,   2446, ...,      0,      0,      0],
       [   827,  14058,    288, ...,      0,      0,      0],
       [   451, 128584,   3627, ...,      0,      0,      0],
       ...,
       [     8,    149,     10, ...,      0,      0,      0],
       [     8,     39,    244, ...,      0,      0,      0],
       [  1104,     24,    958, ...,      0,      0,      0]], dtype=int64)

In [31]:
train=dataset.take(int(len(dataset)*.7))
val=dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test=dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [32]:
train_generator=train.as_numpy_iterator()

In [33]:
train_generator.next()

(array([[    70,   1177,      3, ...,      0,      0,      0],
        [    21,   2180,      4, ...,      0,      0,      0],
        [   929,    655,     46, ...,      0,      0,      0],
        ...,
        [    50,   3004,   1934, ...,      0,      0,      0],
        [    37, 172159,     51, ...,      0,      0,      0],
        [    71,     10,      9, ...,      0,      0,      0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

### Create sequential model:

In [34]:
from tensorflow.keras.models import Sequential

In [35]:
from tensorflow.keras.layers import LSTM ,Dropout,Bidirectional,Dense,Embedding

In [36]:
model= Sequential()
model.add(Embedding(NB_W+1,32))
model.add(Bidirectional(LSTM(32,activation='tanh')))
model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(6,activation='sigmoid'))

In [37]:
model.compile(loss='BinaryCrossentropy',optimizer='Adam')


In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirectiona  (None, 64)               16640     
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [39]:
histoty=model.fit(train,epochs=1,validation_data=val)

6981/6981 [==============================] - 9583s 1s/step - loss: 0.0614 - val_loss: 0.0457


### Make Predictions

In [56]:
input_text=vectorizer('You freaking suck!')

In [57]:
batch=test.as_numpy_iterator().next()

In [58]:
batch=test.as_numpy_iterator().next()

In [59]:
res=model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 0s 116ms/step


In [60]:
input_text

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([   7, 7158,  397, ...,    0,    0,    0], dtype=int64)>

In [61]:
res

array([[0.9838235 , 0.08092296, 0.88623554, 0.00808643, 0.6532609 ,
        0.06135663]], dtype=float32)

In [62]:
batch_X,batch_y=test.as_numpy_iterator().next()

In [63]:
(model.predict(batch_X)>0.5).astype(int)

1/1 [==============================] - 0s 205ms/step


array([[1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [64]:
batch_y

array([[1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

### Evaluating the model

In [67]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [68]:
pre=Precision()

In [70]:
re=Recall()
acc=CategoricalAccuracy()

In [71]:
for batch in test.as_numpy_iterator():
    x_true,y_true=batch
    y_hat=model.predict(x_true)
    
    y_true=y_true.flatten()
    y_hat=y_hat.flatten()
    
    pre.update_state(y_true,y_hat)
    re.update_state(y_true,y_hat)
    acc.update_state(y_true,y_hat)
    

1/1 [==============================] - 0s 155ms/step


1/1 [==============================] - 0s 165ms/step


1/1 [==============================] - 0s 199ms/step


1/1 [==============================] - 0s 160ms/step


1/1 [==============================] - 0s 184ms/step


1/1 [==============================] - 0s 170ms/step


1/1 [==============================] - 0s 158ms/step


In [72]:
print(f'Precision:{pre.result().numpy()},Recall:{re.result().numpy()},Accuracy:{acc.result().numpy()}')

Precision:0.8691328763961792,Recall:0.6248212456703186,Accuracy:0.4974924921989441


### Gradio

In [73]:
!pip install gradio jinja2

     --------------------------------------- 17.3/17.3 MB 17.2 MB/s eta 0:00:00
     ---------------------------------------- 50.5/50.5 kB ? eta 0:00:00
     ---------------------------------------- 224.5/224.5 kB ? eta 0:00:00
     ------------------------------------- 477.4/477.4 kB 29.2 MB/s eta 0:00:00
     ---------------------------------------- 195.1/195.1 kB ? eta 0:00:00
     ---------------------------------------- 58.3/58.3 kB 3.0 MB/s eta 0:00:00
     ---------------------------------------- 319.8/319.8 kB ? eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ------------------------------------- 287.9/287.9 kB 17.4 MB/s eta 0:00:00
     ---------------------------------------- 1.1/1.1 MB 24.2 MB/s eta 0:00:00
     ---------------------------------------- 75.3/75.3 kB 4.3 MB/s eta 0:00:00
     ---------------------------------------- 84.5/84.5 kB ? eta 0:00:00
     ---------------------------------------- 2.

In [74]:
import gradio as gr

In [76]:
model.save('toxicity.h5')

In [87]:
def score_comment(comment):
    vect=vectorizer([comment])
    res=model.predict(vect)
    text=' '
    for i,col in enumerate(df.columns[2:]):
        text+='{} : {}\n'.format(col,res[0][i]>0.5)
    return text
    
    
    

In [88]:
interface= gr.Interface(fn=score_comment,
                       inputs=gr.inputs.Textbox(lines=2,placeholder='...'),
                       outputs='text')

In [89]:
interface.launch()

Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.


1/1 [==============================] - 0s 109ms/step
